runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"
- name: MySQLdb
  version: "latest"

builtins:
- django_wsgi: on

handlers:
- url: /static
  static_dir: static/

env_variables:
  DJANGO_SETTINGS_MODULE: 'Survey.settings'
